version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=barbershop.settings
      - DATABASE_URL=mysql://newuser:+newuser+@db:3306/barbershop_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=barbershop_db
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=+newuser+
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"

volumes:
  mysql_data: 