# Generated by Django 5.2.4 on 2025-07-15 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='Hora de fin del descanso (opcional)', null=True, verbose_name='fin del descanso'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Hora de inicio del descanso (opcional)', null=True, verbose_name='inicio del descanso'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='interval_minutes',
            field=models.IntegerField(default=30, help_text='Intervalo de tiempo entre citas en minutos', verbose_name='intervalo en minutos'),
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('exception_type', models.CharField(choices=[('holiday', 'Día Festivo'), ('vacation', 'Vacaciones'), ('personal', 'Personal'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo de excepción')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(limit_choices_to={'role': 'barber'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'excepción de horario',
                'verbose_name_plural': 'excepciones de horario',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
